#pragma once

#define BUILD_GAME_STUFF 1
#define BUILD_WITH_OPENGL 1
/* #undef FORCE_OPENGL_ES */
/* #undef BUILD_WITH_MARIADB */
#define BUILD_WITH_SDL3 1
#define BUILD_WITH_SDL3_IMAGE 1
#define BUILD_WITH_SDL3_TTF 1
#define BUILD_WITH_SDL3_MIXER 1
#define BUILD_WITH_GLM 1
#define BUILD_WITH_ASSIMP 1
/* #undef BUILD_WITH_CURL */
/* #undef BUILD_WITH_LIBFCGI */
#define BUILD_WITH_GUI 1
