set(BUILD_GAME_STUFF "1")
set(BUILD_WITH_OPENGL "1")
set(FORCE_OPENGL_ES "0")
set(BUILD_WITH_MARIADB "0")
set(BUILD_WITH_SDL3 "1")
set(BUILD_WITH_SDL3_IMAGE "1")
set(BUILD_WITH_SDL3_TTF "1")
set(BUILD_WITH_SDL3_MIXER "1")
set(BUILD_WITH_GLM "1")
set(BUILD_WITH_ASSIMP "1")
set(BUILD_WITH_CURL "0")
set(BUILD_WITH_LIBFCGI "0")
set(BUILD_WITH_GUI "1")

set_property(GLOBAL PROPERTY Tilc_HEADERS_Property "")
set_property(GLOBAL PROPERTY Tilc_SOURCES_Property "")
set_property(GLOBAL PROPERTY Tilc_PLATFORM_SPECIFIC_HEADERS_Property "")
set_property(GLOBAL PROPERTY Tilc_PLATFORM_SPECIFIC_SOURCES_Property "")
set_property(GLOBAL PROPERTY BuildGameStuff BUILD_GAME_STUFF)
set_property(GLOBAL PROPERTY BuildWithMariaDb BUILD_WITH_MARIADB)
set_property(GLOBAL PROPERTY BuildWithSDL3 BUILD_WITH_SDL3)
set_property(GLOBAL PROPERTY BuildWithSDL3Image BUILD_WITH_SDL3_IMAGE)
set_property(GLOBAL PROPERTY BuildWithSDL3Ttf BUILD_WITH_SDL3_TTF)
set_property(GLOBAL PROPERTY BuildWithSDL3Mixer BUILD_WITH_SDL3_MXER)
set_property(GLOBAL PROPERTY BuildWithGlm BUILD_WITH_GLM)
set_property(GLOBAL PROPERTY BuildWithAssimp BUILD_WITH_ASSIMP)
set_property(GLOBAL PROPERTY BuildWithCurl BUILD_WITH_CURL)
set_property(GLOBAL PROPERTY BuildWithLibFcgi BUILD_WITH_LIBFCGI)
set_property(GLOBAL PROPERTY BuildWithGui BUILD_WITH_GUI)

set(CURL_VERSION "curl-8.21.0_5-win64-mingw")
set(URL_CURL_PRECOMPILED_BINARIES "https://curl.se/windows/dl-8.21.0_5/${CURL_VERSION}.zip")
set(URL_CURL_EXPECTED_HASH "4c48761e9b70f447af76e65564cf2afbbf626e4ea6286008fde5cc068de237fd")

# Below is location of lib.exe file needed to generate lib file for dll file. It is used for example for genrating curl.lib for curl.dll.
set(VS_BINARIES "c:/Program Files/Microsoft Visual Studio/18/Community/VC/Tools/MSVC/14.51.36231/bin/Hostx64/x64")

configure_file(Tilc/configure.h.in configure.h)
