#pragma once

#include <string>
#include <sstream>
#include <unordered_map>
#include <filesystem>
#include "Tilc/DllGlobals.h"
#include "Tilc/Utils/FileUtils.h"

namespace Tilc::Resources {

	struct DECLSPEC TResourceInfo
	{
        Tilc::TExtString m_SourceType{};	// SourceType: [File, Stream]
        Tilc::TExtString m_Type{};			// type: [SDL_Surface, SDL_Texture, GL_Texture]
        Tilc::TExtString m_Source{};		// source: File Path for File resource or Name (File Path for sqlite) of database from which retrieve resource
        Tilc::TExtString m_SourceName{};	// name of resource in database (only for Stream resources, empty for File resources)
		int m_SlotNumber{};			// Slot number for Stream resources read from database
        int m_Width{};                // rasterization Width specified for svg files otherwise taken from size of surface
        int m_Height{};               // rasterization Height specified for svg files otherwise taken from size of surface
	};

	class DECLSPEC TResource
	{
	public:
		TResource(void* Resource) { m_Resource = Resource; }
		virtual ~TResource() {}
        void* m_Resource{ nullptr };
		
	};

	// Derived - derived class of TResourceManager class that handles loading specific resources. It is used in Load method
	// T - Resource class TypeName
	template<typename Derived, typename T>
	class TResourceManager
	{
	public:
		TResourceManager(const std::string& PathsFileName)
		{
			LoadSources(PathsFileName);
		}
		virtual ~TResourceManager()
		{
			PurgeResources();
		}
		// Retrieve a particular resource
		T* GetResource(const std::string& Id)
		{
			auto ResourceItem = Find(Id);
			return (ResourceItem ? ResourceItem->first : nullptr);
		}
		// Add a particular resource that can also be generated by game
		T* AddResource(const Tilc::TExtString& Id, T* Resource)
		{
            if (Resource)
            {
                auto ResourceItem = Find(Id);
                if (!ResourceItem)
                {
                    m_Resources.emplace(Id, std::make_pair(Resource, 1));
                    return Resource;
                }
            }
            return nullptr;
		}
		// Retrieve source of a particular resource
		std::string GetSource(const std::string& Id)
		{
			auto Info = m_ResourcesInfos.find(Id);
			return(Info != m_ResourcesInfos.end() ? Info->second.m_Source : "");
		}
		bool RequireResource(const std::string& Id);
		bool ReleaseResource(const std::string& Id);
        void LoadSources(const std::string& SourcesFileName);
        void PurgeResources();
		// Because different resources can have different natures, so to load them it may require to implement subclas off TResourceManager and define in it
		// custom Load method that handles differentations. In this class there is method Load that cesses loading to that custom Load method.
		T* Load(const TResourceInfo& ResourceInfo)
		{
			return static_cast<Derived*>(this)->Load(ResourceInfo);
		}
		T* LoadFromFile(const Tilc::TExtString& FileName, const Tilc::TExtString& ResourceType)
		{
			return static_cast<Derived*>(this)->LoadFromFile(FileName, ResourceType);
		}
	protected:
		std::pair<T*, unsigned int>* Find(const std::string& Id)
		{
			auto Itr = m_Resources.find(Id);
			return (Itr != m_Resources.end() ? &Itr->second : nullptr);
		}
		bool Unload(const std::string& Id) {
			auto Itr = m_Resources.find(Id);
			if (Itr == m_Resources.end())
			{
				return false;
			}
			delete Itr->second.first;
			m_Resources.erase(Itr);
			return true;
		}
	private:
		// Map of: Id -> [ResourceTypeName -> Counter of Resource references]
		std::unordered_map<std::string, std::pair<T*, unsigned int>> m_Resources;
		// Map of: Id -> ResourceInfo
		std::unordered_map<std::string, TResourceInfo> m_ResourcesInfos;
	};


	template<typename Derived, typename T>
	bool TResourceManager<Derived, T>::RequireResource(const std::string& Id)
	{
		auto ResourceItem = Find(Id);
		if (ResourceItem)
		{
			++ResourceItem->second;
			return true;
		}

		auto Info = m_ResourcesInfos.find(Id);
		if (Info == m_ResourcesInfos.end())
		{
			return false;
		}

		T* Resource = Load(Info->second);
		if (!Resource)
		{
			return false;
		}
		m_Resources.emplace(Id, std::make_pair(Resource, 1));
		return true;
	}

	template<typename Derived, typename T>
	bool TResourceManager<Derived, T>::ReleaseResource(const std::string& Id) {
		auto ResourceItem = Find(Id);
		if (!ResourceItem)
		{
			return false;
		}
		--ResourceItem->second;
		if (ResourceItem->second == 0)
		{
			Unload(Id);
		}
		return true;
	}

	template<typename Derived, typename T>
	void TResourceManager<Derived, T>::LoadSources(const std::string& PathsFileName)
	{
		if (FileExists((std::filesystem::current_path().string() + "/" + PathsFileName).c_str()))
		{
			Tilc::TFile File((std::filesystem::current_path().string() + "/" + PathsFileName).c_str());
			if (File.m_File.is_open())
			{
				std::string Line;
				while (std::getline(File.m_File, Line))
				{
					TResourceInfo Info;
					std::stringstream KeyStream(Line);
					std::string ResourceName;
					KeyStream >> ResourceName;
					KeyStream >> Info.m_SourceType;
					KeyStream >> Info.m_Type;
					KeyStream >> Info.m_Source;
					if (!KeyStream.eof())
					{
						KeyStream >> Info.m_SourceName;
					}
					else
					{
						Info.m_SourceName = "";
					}
					if (!KeyStream.eof())
					{
						KeyStream >> Info.m_SlotNumber;
					}
					else
					{
						Info.m_SlotNumber = -1;
					}
					m_ResourcesInfos.emplace(ResourceName, Info);
				}
				return;
			}
		}
		else
			SDL_Log("Resources path file: %s not exists. Skipping...", PathsFileName.c_str());
	}

    template<typename Derived, typename T>
    void TResourceManager<Derived, T>::PurgeResources()
    {
        while (m_Resources.begin() != m_Resources.end())
        {
            delete m_Resources.begin()->second.first;
            m_Resources.erase(m_Resources.begin());
        }
    }
}
