#pragma once

#include "Tilc/DllGlobals.h"
#include "Tilc/Resources/ResourceManager.h"
#include <SDL3/SDL.h>
#define GLAD_GL_IMPLEMENTATION
#ifdef APIENTRY
# undef APIENTRY
#endif
#include <glad/glad.h>
#ifdef APIENTRY
# undef APIENTRY
#endif

namespace Tilc::Resources
{
	enum class ETextureType
	{
		None,
		SDL_Surface,
		SDL_Texture,
		GL_Texture
	};

	class DECLSPEC TResourceTexture : public TResource
	{
	public:
		TResourceTexture(void* Resource) : TResource(Resource) {}
		virtual ~TResourceTexture();
		SDL_Surface* AsSDLSurface()
		{
			if (m_TextureType == ETextureType::SDL_Surface)
			{
				return reinterpret_cast<SDL_Surface*>(m_Resource);
			}
			return nullptr;
		}
		SDL_Texture* AsSDLTexture()
		{
			if (m_TextureType == ETextureType::SDL_Texture)
			{
				return reinterpret_cast<SDL_Texture*>(m_Resource);
			}
			return nullptr;
		}
		GLuint AsGLTexture()
		{
			if (m_TextureType == ETextureType::GL_Texture)
			{
				unsigned long long Result = reinterpret_cast<unsigned long long>(m_Resource);
				return Result;
			}
			return 0;
		}
		ETextureType m_TextureType;
		SDL_PixelFormat m_Format;
		int m_TexWidth = 0;
		int m_TexHeight = 0;
	};

	class DECLSPEC TTextureManager : public TResourceManager<TTextureManager, TResourceTexture>
	{
	public:
		TTextureManager(const std::string& PathsFileName = "data/Resources.cfg") : TResourceManager(PathsFileName) {}
		TResourceTexture* Load(const TResourceInfo& ResourceInfo);
        // Rasterization width and height are taken in account for svg files.
		TResourceTexture* LoadFromFile(const Tilc::TExtString& FileName, const Tilc::TExtString& ResourceType, int RasterizationWidth = -1, int RasterizationHeight = -1);
		TResourceTexture* CreateGLTextureResourceFromSDLSurface(SDL_Surface* Surface);
        // Add a resource from file that can also be generated by game
        TResourceTexture* AddResourceFromFile(const Tilc::TExtString& Id, const Tilc::TExtString& FileName, const Tilc::TExtString& ResourceType)
        {
            TResourceTexture* Resource = LoadFromFile(FileName, ResourceType);
            if (Resource)
            {
                return AddResource(Id, Resource);
            }
            return nullptr;
        }
    };

}
