#define SDL_MAIN_USE_CALLBACKS 1
#include <SDL3/SDL.h>
#include <SDL3/SDL_main.h>

#define SCR_WIDTH 800
#define SCR_HEIGHT 600

#include <string>
#include <iostream>
#include <vector>
#include <chrono>
#include <filesystem>
#include "Tilc/Tilc.h"


class TStaticMesh : public Tilc::Graphics::TMesh
{
public:
	TStaticMesh(Tilc::Graphics::OpenGL::TPipeline* Pipeline);
};
TStaticMesh* Mesh = nullptr;
Tilc::Graphics::OpenGL::TPipeline* Pipeline;

SDL_AppResult SDL_AppInit(void** appstate, int argc, char* argv[])
{
	std::string WindowTitle("Camera");
	SDL_SetAppMetadata(WindowTitle.c_str(), "1.0", "pl.net.progmar.camera");

	Tilc::GameObject = new Tilc::TGame(Tilc::EGameType::Game3D);
	SDL_AppResult Result = Tilc::InitTilc(WindowTitle, SCR_WIDTH, SCR_HEIGHT, false, true);
	if (Result != SDL_APP_CONTINUE)
	{
		return Result;
	}
	//SDL_Log("Current Directory: %s\n", std::filesystem::current_path().string().c_str());


	// Load OpenGL entry points using glad. Must be here alse because dll have its own pointers to gl functions that are not visible to exe file
	gladLoadGL();

	Pipeline = new Tilc::Graphics::OpenGL::TPipeline(
R"(
#version 450 core
#extension GL_ARB_separate_shader_objects: enable

layout (location = 0) in vec3 VertexPos;
layout (location = 1) in vec3 VertexColor;
layout (location = 2) in vec2 VertexTexCoord;

out vec3 VertColor;
out vec2 VertTexCoord;

out gl_PerVertex
{
    vec4 gl_Position;
    float gl_PointSize;
    float gl_ClipDistance[];
};

layout (location = 0) uniform mat4 Model;

void main()
{
	gl_Position = Model * vec4(VertexPos, 1.0f);
    VertColor = VertexColor;
    VertTexCoord = VertexTexCoord;
})",


R"(
#version 450 core
in vec3 VertColor;
in vec2 VertTexCoord;
out vec4 FragColor;

layout (binding = 0) uniform sampler2D tex;

void main()
{
	//FragColor = vec4(VertColor, 1.0f);
	FragColor = vec4(texture(tex, VertTexCoord).rgb, 1.0f);
})",


""
	);
	if (!Pipeline)
	{
		SDL_Log("Error: Unable to create Pipeline\n");
		return SDL_APP_FAILURE;
	}

	Mesh = new TStaticMesh(Pipeline);
	if (!Mesh)
	{
		SDL_Log("Error: Unable to create Mesh\n");
		return SDL_APP_FAILURE;
	}

	Tilc::GameObject->AddCamera({ 0.0f, 0.0f, -2.0f }, { 1.0f, 0.0f, 0.0f }, { 0.0f, 1.0f, 0.0f });
	SDL_HideCursor();

	return SDL_APP_CONTINUE;  /* carry on with the program! */
}


SDL_AppResult SDL_AppEvent(void* appstate, SDL_Event* event)
{
	return Tilc::GameObject->GetContext()->m_EventManager->HandleEvent(event);
}

SDL_AppResult SDL_AppIterate(void* appstate)
{
	static SDL_Window* window = Tilc::GameObject->GetContext()->m_Window->GetRenderWindow();

	Tilc::GameObject->Update();

	// We want to rotate cube around point (-1.0f, -1.0f, 0.0f) in direction z-axis
	Tilc::TVector3D<float> v{ 0.0f, 0.0f, 8.0f };
	// so before rotating we must translate our model to point (-1.0f, -1.0f, 0.0f)
	//Tilc::TMatrix4<float> ModelMatrix = Tilc::Translate(Tilc::TMatrix4<float>(1.0f), v);
	// Apply rotation to it
	Tilc::TMatrix4<float> ModelMatrix(1.0f);
	ModelMatrix = Tilc::RotateAroundVector(ModelMatrix, Tilc::GameObject->m_TotalElapsed / 1000.0f, Tilc::TVector3D<float>(0.0f, 0.0f, 1.0f));
	// and translate back in opposite direction
	ModelMatrix = Tilc::Translate(ModelMatrix, -v);

	Tilc::TMatrix4<float> ProjectionMatrix = Tilc::Perspective(45.0f, static_cast<float>(SCR_WIDTH) / SCR_HEIGHT, 1.0f, 50.0f);

	Tilc::TMatrix4<float> MVPMatrix = ProjectionMatrix * Tilc::GameObject->GetCurrentCamera()->UpdateViewMatrix() * ModelMatrix;

	glViewport(0, 0, SCR_WIDTH, SCR_HEIGHT);
	glClearColor(0.3f, 0.3f, 0.3f, 1.0f);
	// We turn off depth testing and face culling to see how blending draws transparent faces of cube making it translucent
	glEnable(GL_DEPTH_TEST);
	// Setting below is optimalization that causes that there are drawn two times less triangles than withou it
	glEnable(GL_CULL_FACE);
	// Below is the default OpenGL setting so calling it not changes our scene, because triangles drawn are already sorted in counter clock wise direction
	glFrontFace(GL_CCW);
	// Cd - Color default, Fd - factor of color default
	// Cs - Color from shader, Fs - factor of color from shader
	// C = Cd * Fd + Cs * Fs
	//glEnable(GL_BLEND);
	// In function below first param is Fs from formula above and second param is Fd from formula above
	// GL_SRC_ALPHA as first param means that we want to use alhpha value outputed in alpha value of color generated by fragment shader
	//glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);

	glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
	
	if (Mesh->m_DoRender)
	{
		Mesh->m_Pipeline->Bind();
		Mesh->m_Pipeline->SetMat4(Mesh->m_Pipeline->m_VertexShader, "Model", MVPMatrix.Elems);
		Mesh->Render(GL_TRIANGLES, true);
	}
	SDL_GL_SwapWindow(window);

	Tilc::GameObject->LateUpdate();
	return SDL_APP_CONTINUE;
}

void SDL_AppQuit(void* appstate, SDL_AppResult result)
{
	if (Tilc::GameObject->GetContext()->m_TextureManager)
	{
		Tilc::GameObject->GetContext()->m_TextureManager->ReleaseResource("Wood");
	}

	if (Mesh)
	{
		delete Mesh;
		Mesh = nullptr;
	}

	if (Pipeline)
	{
		delete Pipeline;
		Pipeline = nullptr;
	}

	SDL_Log("App Quit: Application was being running by %lu seconds", SDL_GetTicks() / 1000);
}




TStaticMesh::TStaticMesh(Tilc::Graphics::OpenGL::TPipeline* Pipeline)
	: Tilc::Graphics::TMesh(Pipeline)
{
	LoadUnitCubeData16();

	m_VertexComponents.push_back({ Tilc::Graphics::EVertexComponent::EVC_Position, 3, glGetAttribLocation(Pipeline->m_VertexShader, "VertexPos"), 0 });
	m_VertexComponents.push_back({ Tilc::Graphics::EVertexComponent::EVC_Color, 3, glGetAttribLocation(Pipeline->m_VertexShader, "VertexColor"), 4 });
	m_VertexComponents.push_back({ Tilc::Graphics::EVertexComponent::EVC_TexCoord, 2, glGetAttribLocation(Pipeline->m_VertexShader, "VertexTexCoord"), 8 });
	SetStrideElemsCount(14);

	if (Tilc::GameObject->GetContext()->m_TextureManager->RequireResource("Wood"))
	{
		m_Textures.push_back({ 0, Tilc::GameObject->GetContext()->m_TextureManager->GetResource("Wood")->AsGLTexture() });
	}

	CreateVAOAndBuffers<Tilc::float16, GLubyte>(24);
}
